import os
from datetime import datetime
from dotenv import load_dotenv
from google import genai

# -----------------------------
# Load API Key
# -----------------------------
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, ".env"))

api_key = os.getenv("GEMINI_API_KEY")

client = None

if api_key:
    client = genai.Client(api_key=api_key)


# -----------------------------
# Offline Assistant
# -----------------------------
def offline_response(prompt):

    text = prompt.lower()

    if "hello" in text or "hi" in text:
        return "Hello! Nice to meet you. How can I help you?"

    elif "your name" in text:
        return "I am an AI Voice Assistant developed using Python, Whisper, Gemini AI and Streamlit."

    elif "time" in text:
        return f"The current time is {datetime.now().strftime('%I:%M %p')}."

    elif "date" in text:
        return f"Today's date is {datetime.now().strftime('%d %B %Y')}."

    elif "who made you" in text:
        return "I was developed as a Final Year AI Voice Assistant project."

    elif "machine learning" in text:
        return (
            "Machine learning is a branch of Artificial Intelligence "
            "that enables computers to learn from data without being "
            "explicitly programmed."
        )

    elif "artificial intelligence" in text:
        return (
            "Artificial Intelligence is the simulation of human intelligence "
            "by computer systems."
        )

    elif "python" in text:
        return (
            "Python is a popular programming language widely used in "
            "Artificial Intelligence, Machine Learning and Data Science."
        )

    elif "thank" in text:
        return "You're welcome."

    elif "bye" in text:
        return "Goodbye! Have a wonderful day."

    else:
        return (
            "The online AI service is currently unavailable. "
            "This is an offline response generated by the local assistant."
        )


# -----------------------------
# Gemini Function
# -----------------------------
def ask_gemini(prompt):

    if client is None:
        return offline_response(prompt)

    try:

        response = client.models.generate_content(
            model="models/gemini-flash-latest",
            contents=prompt
        )

        if hasattr(response, "text") and response.text:
            return response.text

        return offline_response(prompt)

    except Exception as e:

        print("Gemini Error:", e)

        return offline_response(prompt)


# -----------------------------
# Test
# -----------------------------
if __name__ == "__main__":

    while True:

        question = input("You: ")

        if question.lower() == "exit":
            break

        print("\nAssistant:", ask_gemini(question))